## Assignment 1: Make a Cultist Model
* import the data from the dataset, and store it in a pandas variable cult
* Divide the data into two datasets, cultists and roles. Make the X dataset for  the stats(features) of the cultists, and the Y dataset for the position(targets) for the dataset.
* Refactor the dataset cultists, by removing the irrelevent features from in the dataset, so it only contains charactistic statistics
 ['stealth', 'Influence', 'Endurance', 'Lore', 'Economic', 'Strength', 'Insanity']
* Refactor the dataset roles so each value become machine friendly numbers, instead of strings.
* Use LinearRegression to make a model object.
* Use train_test_split from model_selection, to make training and testing dataset from cultists and roles
* Try atjusting the test_size variable later, to see what gives the better scores.
* Feed the model with the training datasets, and score the model on the training dataset (model.score)
* Score the model on the testing datasets, and compare to the testing scores.

In [1]:
import numpy as np
import pandas as pd

#Use pandas to read data into pd frame
data = pd.read_csv('https://raw.githubusercontent.com/Micniks/Python-Week11-Group-3-Assignments/main/cultists.csv')
print(data.head())

             Cultist  Stealth  Influence  Endurance  Lore  Economic  Strength  \
0     Nellie Simpson      7.5        6.0        1.3   3.4       8.5       0.1
1        Brad Garner      8.6        7.1        5.6   4.3       8.9       8.0
2    Kristen Watkins      0.1        4.7        2.9   4.6       2.2       5.6
3    Marcella Peters      7.1        1.4        4.5   0.5       1.4       4.0
4  Vivian Montgomery      2.3        5.4        5.1   7.5       3.4       1.3

   Insanity    Position   Age  Membership_in_years  Contribution_in_dollars  \
0       9.7   Recruiter  56.0                   24                     7137
1       0.9  Accountant  27.0                   12                     3266
2       8.6      Priest  23.0                    8                      442
3       5.8    Assassin  45.0                    2                      126
4       6.0      Priest  56.0                   26                     2654

   Members_recruited Type_of_living_area
0                162                City
1                  0                City
2                  8                City
3                  0            Province
4                 14                City

####  Divide the data into two datasets, cultists and roles. Make the X dataset for  the stats(features) of the cultists, and the Y dataset for the position(targets) for the dataset.
#### Refactor the dataset cultists, by removing the irrelevent features from in the dataset, so it only contains charactistic statistics
 ['stealth', 'Influence', 'Endurance', 'Lore', 'Economic', 'Strength', 'Insanity']

#### Refactor the dataset roles so each value become machine friendly numbers, instead of strings.

In [2]:
#Dropping unrelated columns (features/observations)

X = np.array(data.drop(columns=['Cultist','Position','Age','Membership_in_years','Contribution_in_dollars','Members_recruited','Type_of_living_area']))

#getting the response data
y = data[['Position']]

#converting the y data (labels) into machine friendly numbers
label_mapping = {
    'Priest':0, 
    'Enforcer':1, 
    'Assassin':2, 
    'Recruiter':3,
    'Accountant':4,
    'Advisor':5
}

print('Before converting to machine friendly numbers: \n',y[:5])
y['Position'] = y['Position'].map(label_mapping)

y = np.array(y)

print('After converting:\n',y[:5])

print(X.shape)
print(y.shape)

Before converting to machine friendly numbers:
      Position
0   Recruiter
1  Accountant
2      Priest
3    Assassin
4      Priest
After converting:
 [[3]
 [4]
 [0]
 [2]
 [0]]
(6666, 7)
(6666, 1)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

#### Use LinearRegression to make a model object.

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

model = LinearRegression()

#### Use train_test_split from model_selection, to make training and testing dataset from cultists and roles

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

model.fit(X_train,y_train)

(3999, 7)
(2667, 7)
(3999, 1)
(2667, 1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

#### Feed the model with the training datasets, and score the model on the training dataset (model.score)
#### Score the model on the testing datasets, and compare to the testing scores.

In [5]:
y_pred = model.predict(X_test)
print(len(y_pred))

2667

In [6]:
result_test = model.score(X_test, y_test)
print(result_test)

result_train = model.score(X_train, y_train)
print(result_train)

0.49080098743814016
0.5046848337954937

## Assignment 2: Classification of Cultists
##### Since the cultist data doesn't seem to have any linear progression, another model might give better result in sorting members...

* Use DecisionTreeClassifier to make a new model object
* Use train_test_split from model_selection, to make training and testing dataset from cultists and roles
* Try atjusting the test_size variable later, to see what gives the better scores.
* Feed the model with the training datasets, and score the model on the training dataset (accuracy _score from sklearn.metrics)
* Score the model on the testing datasets, and compare to the testing scores.
* Compare the scores from using Classification and using Regression models. We suspect the score difference is the result of the datasets structure not progressing in a linear fashion

In [7]:
from sklearn.tree import DecisionTreeClassifier


model2 = DecisionTreeClassifier(max_leaf_nodes=20, random_state=0)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

model2.fit(X_train,y_train)

y_pred2 = model2.predict(X_test)
print(len(y_pred2))

(3999, 7)
(2667, 7)
(3999, 1)
(2667, 1)
2667

In [8]:
from sklearn.metrics import accuracy_score

result = model2.score(X_test, y_test)
print(result)

result = model2.score(X_train, y_train)
print(result)

0.5905511811023622
0.6349087271817955

## Assignment 3: Find Clusters of Cultists
* Use the orignal dataset again, and remove the charactistic statistics used earlier, as well as the name and position for each member.
* Change the Living_Area feature into multiple numeric features, using One Hot Encoding
* Remove all rows with missing data for any features
* Make a model/analyzer from sklearn.cluster, with the appropriate bandwidth for the data.
* Use the analyzer to process the data, grouping people into clusters.
* Make a dataset from the cluster-array, showing the avarage statistic values for features in each cluster
* Add a count feature to each cluster, showing how many members are in each cluster
* Look at the final data, and answer the following questions:
    * How many clusters are there
    * Which cluster has the highest amount of recruits
    * What seems to be the defining feature(s) for each cluster

In [9]:
X1 = data.drop(columns=['Cultist','Position'])
X1.head()

,Stealth,Influence,Endurance,Lore,Economic,Strength,Insanity,Age,Membership_in_years,Contribution_in_dollars,Members_recruited,Type_of_living_area
0,7.5,6.0,1.3,3.4,8.5,0.1,9.7,56.0,24,7137,162,City
1,8.6,7.1,5.6,4.3,8.9,8.0,0.9,27.0,12,3266,0,City
2,0.1,4.7,2.9,4.6,2.2,5.6,8.6,23.0,8,442,8,City
3,7.1,1.4,4.5,0.5,1.4,4.0,5.8,45.0,2,126,0,Province
4,2.3,5.4,5.1,7.5,3.4,1.3,6.0,56.0,26,2654,14,City

#### Change the Living_Area feature into multiple numeric features, using One Hot Encoding

In [10]:
from sklearn import preprocessing

label_enc =preprocessing.LabelEncoder()
X1 = pd.get_dummies(X1,columns=['Type_of_living_area'])
X1.head()

,Stealth,Influence,Endurance,Lore,Economic,Strength,Insanity,Age,Membership_in_years,Contribution_in_dollars,Members_recruited,Type_of_living_area_City,Type_of_living_area_Province,Type_of_living_area_Rural
0,7.5,6.0,1.3,3.4,8.5,0.1,9.7,56.0,24,7137,162,1,0,0
1,8.6,7.1,5.6,4.3,8.9,8.0,0.9,27.0,12,3266,0,1,0,0
2,0.1,4.7,2.9,4.6,2.2,5.6,8.6,23.0,8,442,8,1,0,0
3,7.1,1.4,4.5,0.5,1.4,4.0,5.8,45.0,2,126,0,0,1,0
4,2.3,5.4,5.1,7.5,3.4,1.3,6.0,56.0,26,2654,14,1,0,0

#### Remove all rows with missing data for any features

In [11]:
print('rows before drop n/a',len(X1))
X1_filtered = X1.dropna()
print('rows after',len(X1_filtered))

rows before drop n/a 6666
rows after 6640

#### Make a model/analyzer from sklearn.cluster, with the appropriate bandwidth for the data.
#### Use the analyzer to process the data, grouping people into clusters.

In [12]:
from sklearn.cluster import MeanShift, estimate_bandwidth
analyzer = MeanShift(bandwidth=550) 

analyzer.fit(X1_filtered)

labels = analyzer.labels_
X1_filtered['cluster_group'] = np.nan
data_length=len(X1_filtered)
for i in range(data_length): 
    X1_filtered.iloc[i,X1_filtered.columns.get_loc('cluster_group')] = labels[i] #set the cluster label on each row

X1_filtered

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/opt/conda/lib/python3.7/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,Stealth,Influence,Endurance,Lore,Economic,Strength,Insanity,Age,Membership_in_years,Contribution_in_dollars,Members_recruited,Type_of_living_area_City,Type_of_living_area_Province,Type_of_living_area_Rural,cluster_group
0,7.5,6.0,1.3,3.4,8.5,0.1,9.7,56.0,24,7137,162,1,0,0,2.0
1,8.6,7.1,5.6,4.3,8.9,8.0,0.9,27.0,12,3266,0,1,0,0,1.0
2,0.1,4.7,2.9,4.6,2.2,5.6,8.6,23.0,8,442,8,1,0,0,0.0
3,7.1,1.4,4.5,0.5,1.4,4.0,5.8,45.0,2,126,0,0,1,0,0.0
4,2.3,5.4,5.1,7.5,3.4,1.3,6.0,56.0,26,2654,14,1,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6661,1.1,3.2,5.2,9.5,8.2,5.6,0.2,65.0,50,12700,0,1,0,0,6.0
6662,9.9,8.0,6.0,7.9,3.2,5.5,2.7,62.0,28,3573,0,0,1,0,1.0
6663,9.2,6.7,3.5,7.4,9.2,6.6,1.0,49.0,34,9926,0,1,0,0,4.0
6664,6.7,7.7,7.7,4.0,2.4,7.0,4.1,61.0,16,1490,6,1,0,0,0.0
6665,8.2,9.5,7.6,9.8,10.0,1.0,9.8,37.0,22,6823,168,1,0,0,2.0

#### Make a dataset from the cluster-array, showing the avarage statistic values for features in each cluster
#### Add a count feature to each cluster, showing how many members are in each cluster

In [13]:
#Grouping passengers by Cluster
X1_cluster_data = X1_filtered.groupby(['cluster_group']).mean()
#Count of passengers in each cluster
X1_cluster_data['Counts'] = pd.Series(X1_filtered.groupby(['cluster_group']).size())
print(X1_cluster_data)

                Stealth  Influence  Endurance      Lore  Economic  Strength  \
cluster_group
0.0            4.896359   4.939348   4.973451  5.017201  3.695000  4.971630
1.0            5.154718   4.932344   4.936202  4.933234  5.715786  5.002730
2.0            4.951830   5.000963   5.110212  4.795183  6.730058  4.884586
3.0            5.172109   5.151361   5.069388  5.212585  7.624830  5.044218
4.0            5.317683   5.235366   5.076829  5.042683  7.832317  5.192073
5.0            5.320408   4.561224   5.085714  5.139796  8.386735  4.756122
6.0            6.084058   4.811594   5.310145  5.084058  8.595652  4.939130
7.0            5.094118   5.300000   5.055882  6.132353  8.829412  4.223529
8.0            6.073529   5.520588   5.241176  5.785294  8.250000  4.829412
9.0            6.020000   5.730000   5.380000  5.170000  9.150000  5.035000
10.0           4.560000   3.560000   6.273333  5.533333  9.360000  4.813333
11.0           3.908333   4.566667   4.300000  4.758333  9.291667  5.083333
12.0           7.527273   7.081818   4.636364  4.718182  9.209091  4.509091
13.0           5.360000   4.140000   3.920000  5.760000  9.480000  2.380000

               Insanity        Age  Membership_in_years  \
cluster_group
0.0            4.977989  41.954076            13.107337
1.0            4.965341  51.315727            25.646291
2.0            5.288825  57.404624            33.408478
3.0            4.864966  59.333333            36.479592
4.0            4.857317  62.890244            40.768293
5.0            4.887755  64.030612            42.755102
6.0            4.963768  64.782609            44.695652
7.0            4.041176  68.500000            48.911765
8.0            4.544118  68.911765            48.176471
9.0            5.600000  70.950000            48.750000
10.0           5.293333  71.200000            50.866667
11.0           3.825000  70.583333            52.083333
12.0           7.518182  74.272727            54.909091
13.0           1.020000  73.600000            56.800000

               Contribution_in_dollars  Members_recruited  \
cluster_group
0.0                        1150.814946          12.972011
1.0                        4145.103264          26.547774
2.0                        6777.620424          36.865125
3.0                        8519.748299          43.863946
4.0                       10050.396341          43.024390
5.0                       11208.000000          39.806122
6.0                       12369.942029          33.942029
7.0                       14073.705882          62.882353
8.0                       13256.323529          56.029412
9.0                       14762.350000          99.050000
10.0                      15513.133333           8.200000
11.0                      16352.750000          30.250000
12.0                      17232.727273         142.727273
13.0                      18250.800000           0.000000

               Type_of_living_area_City  Type_of_living_area_Province  \
cluster_group
0.0                            0.592391                      0.246196
1.0                            0.596439                      0.237982
2.0                            0.564547                      0.267823
3.0                            0.595238                      0.234694
4.0                            0.542683                      0.298780
5.0                            0.612245                      0.183673
6.0                            0.594203                      0.260870
7.0                            0.558824                      0.264706
8.0                            0.676471                      0.176471
9.0                            0.850000                      0.150000
10.0                           0.800000                      0.066667
11.0                           0.750000                      0.166667
12.0                           0.636364                      0.272727
13.0                           0.800000                      0.200000

               Type_of_living_area_Rural  Counts
cluster_group
0.0                             0.156522    3680
1.0                             0.162611    1685
2.0                             0.157996     519
3.0                             0.166667     294
4.0                             0.158537     164
5.0                             0.204082      98
6.0                             0.130435      69
7.0                             0.147059      34
8.0                             0.147059      34
9.0                             0.000000      20
10.0                            0.133333      15
11.0                            0.083333      12
12.0                            0.090909      11
13.0                            0.000000       5

* Look at the final data, and answer the following questions:
    * How many clusters are there
    * Which cluster has the highest amount of recruits
    * What seems to be the defining feature(s) for each cluster

## Conclusion:

#### By using bandwith 550 I managed to cut the clusters-volume down to 14 .. When setting bandwith lower  I got significantly more clusters which made it very hard to analyze the data.

#### Cluster 0.0 has the highest amount of recruits .. 3380

#### I have decided only to include clusters 0.0, 1.0, 2.0 and 3.0 as they constitute more or less the total amount of recruits. The clusters seem to be influenced heavily by the following features:
* Age
* Membership_in_years
* Contribution_in_dollars
* Members_recruited

#### When moving from cluster 0.0 to cluster 3.0, the values in the abovementioned features increases. This is very interesting as it might suggest that there may be some kind of significant correlation between one or more of the features.